#服务器配置
server:
  port: 8100
  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    io-threads: 4
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    worker-threads: 20
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true

#spring配置
spring:
  devtools:
    restart:
      log-condition-evaluation-delta: false
    livereload:
      port: 23333
    redis:
        ##redis 单机环境配置
        host: ${redis.dev.host}
        port: ${redis.dev.port}
        password: ${redis.dev.password}
        database: ${redis.dev.database}
        ssl: ${redis.dev.ssl}
        ##redis 集群环境配置
        #cluster:
        #  nodes: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003
        #  commandTimeout: 5000
#feign配置
feign:
  hystrix:
    enabled: true
  #sentinel:
    #enabled: true
  okhttp:
    enabled: true
  httpclient:
    enabled: false

#hystrix配置
hystrix:
  threadpool:
    default:
      coreSize: 300
      maxQueueSize: 1000
      queueSizeRejectionThreshold: 800
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

#ribbon配置
ribbon:
  #对当前实例的重试次数
  MaxAutoRetries: 1
  #切换实例的重试次数
  MaxAutoRetriesNextServer: 2
  #请求处理的超时时间
  ReadTimeout: 60000
  #请求连接的超时时间
  ConnectTimeout: 60000
  #对所有操作请求都进行重试
  OkToRetryOnAllOperations: true

#对外暴露端口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

#blade配置
hert:
  xss:
    url:
      exclude-patterns:
        - /weixin
  secure:
    url:
      exclude-patterns:
        - /test/**
    client:
      - client-id: sword
        path-patterns:
          - /sword/**
      - client-id: saber
        path-patterns:
          - /saber/**
  tenant:
    column: tenant_code
    tables:
      - blade_notice

